### ISSUE TITLE
Running on Linux (Ubuntu)

### ISSUE THREAD

**Issue by pazuzu216** [scriptituk/xfade-easing#6]
I had to copy vf_xfade.c to vf_xfade-dist.c to get it to patch FFmpeg, no vf_xfade-dist.c anywhere.

To get xfade-easing.sh to run, I had to replace gsed with sed in the script.

But now it works fine. Thanks for all the work put into this project :-)

**Comment by scriptituk** [comment]
Thanks for this.

I have fixed the patch file and amended the build instructions.

Regarding gsed, this is not an Issue per se because the documentation and Bash script make it clear that gsed is a dependency. On Macos sed does not recognise word boundary tokens `\b` or `\<`&`\>`. The script also uses GNU gawk features. If Ubuntu sed works that's great (have you tested say sinusoidal easing radial transition expressions that contain `P` and `PI`?). Some day I might add compatibility tests.

BTW I have just published 4 more transitions: `gl_ButterflyWaveScrawler`, `gl_chessboard`, `gl_CrossZoom, `gl_StereoViewer`.
